spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flowers_db
    username: postgres
    password: nurdau50
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
